version: '3'

services:
  portfolio:
    image: portfolio:1.1  # Use the loaded image name here
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  akordebi:
    image: akordebi:1.3  # Use the loaded image name here
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    depends_on:
      - mysql

  construction_landing:
    image: construction_landing:1.1  # Use the loaded image name here
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    depends_on:
      - mysql

  build365:
    image: build365:1.1  # Use the loaded image name here
    restart: unless-stopped
    ports:
      - "3004:3004"
    environment:
      - PORT=3004

  chords365:
    image: chords365:1.3  # Use the loaded image name here
    restart: unless-stopped
    ports:
      - "3005:3002"
    environment:
      - PORT=3002
    depends_on:
      - mysql

  alarm:
    image: alarm:1.0  # Use the loaded image name here
    restart: unless-stopped
    ports:
      - "3006:3000"
    environment:
      - PORT=3000
    depends_on:
      - mysql

  tsogi_manager:
    image: tsogi_manager:1.0  # Use the loaded image name here
    restart: unless-stopped
    ports:
      - "3007:3008"
    environment:
      - PORT=3008
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: nikoloz93  # Use the actual root password you want to set
      MYSQL_DATABASE: akordebi.ge
      TZ: Asia/Tbilisi
    volumes:
      - mysql-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro  # Mount the host timezone file
      - /etc/timezone:/etc/timezone:ro  # Mount the host timezone file


volumes:
  mysql-data: